language: groovy
jdk:
  - oraclejdk7
  - openjdk7
branches:
  only:
    - master
script: 
    - ./grailsw test-app
    - cd ./zenboot-scripts/internal/scripts/sanity-restcheck && ./010_sanity-restcheck.sh 
